"""empty message

Revision ID: 4e15f3bc88b5
Revises: 9a9f39c4bfdd
Create Date: 2017-11-10 19:49:55.121431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e15f3bc88b5'
down_revision = '9a9f39c4bfdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('gravatar_hash', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'gravatar_hash')
    # ### end Alembic commands ###
