"""empty message

Revision ID: b9ec7d00a64a
Revises: 3efd16b554a7
Create Date: 2017-11-11 23:34:21.830564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9ec7d00a64a'
down_revision = '3efd16b554a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('published', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'published')
    # ### end Alembic commands ###
